# Generated by Django 3.2.9 on 2021-11-01 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('representative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department'),
        ),
    ]
